version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependency
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    labels:
      - dependency
    schedule:
      interval: weekly
    ignore:
      - dependency-name: typescript
